############################################
# CloudTechNext deployment inputs
############################################

variable "tenancy_ocid" {
  description = "Tenancy OCID."
  type        = string

  validation {
    condition     = length(var.tenancy_ocid) > 0
    error_message = "tenancy_ocid cannot be empty."
  }
}

variable "compartment_ocid" {
  description = "Target compartment OCID."
  type        = string

  validation {
    condition     = length(var.compartment_ocid) > 0
    error_message = "compartment_ocid cannot be empty."
  }
}

variable "region" {
  description = "OCI region, for example us-chicago-1."
  type        = string

  validation {
    condition     = length(var.region) > 0
    error_message = "region cannot be empty."
  }
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by CloudTechNext before creating the Resource Manager stack."
  type        = string

  validation {
    condition     = length(var.objectstorage_namespace) > 0
    error_message = "objectstorage_namespace cannot be empty."
  }
}

variable "deployment_suffix" {
  description = "Unique suffix generated by CloudTechNext for this deployment."
  type        = string
  default     = "local0000"

  validation {
    condition     = can(regex("^[a-z0-9]{4,16}$", var.deployment_suffix))
    error_message = "deployment_suffix must be 4 to 16 lowercase alphanumeric characters."
  }
}

variable "bucket_name" {
  description = "Optional legacy Object Storage bucket override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "adb_db_name" {
  description = "Optional legacy Autonomous Database db_name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""

  validation {
    condition     = var.adb_db_name == "" || can(regex("^[A-Za-z][A-Za-z0-9]{1,13}$", var.adb_db_name))
    error_message = "adb_db_name must start with a letter, contain only letters and numbers, and be at most 14 characters."
  }
}

variable "adb_display_name" {
  description = "Optional legacy Autonomous Database display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "vcn_display_name" {
  description = "Optional legacy VCN display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "instance_display_name" {
  description = "Optional legacy compute display name override. Empty derives a unique name from deployment_suffix."
  type        = string
  default     = ""
}

variable "source_repo_url" {
  description = "Published Oracle AI Accelerator Git repository."
  type        = string
  default     = "https://github.com/jgangini/oracle-ai-accelerator.git"
}

variable "source_ref" {
  description = "Git ref to deploy from the published repository."
  type        = string
  default     = "main"
}

############################################
# Bucket
############################################

variable "_oci_bucket_name" {
  description = "Object Storage bucket defaults from upstream setup-tf, parameterized by CloudTechNext."

  default = {
    name        = "buk-oracle-ai"
    access_type = "ObjectRead"
  }
}

############################################
# Oracle Autonomous Database
############################################

variable "_oci_autonomous_database" {
  description = "Autonomous Database profile for CloudTechNext launchpad deployments."

  default = {
    db_name                  = "ora26ai"
    display_name             = "ora26ai"
    compute_count            = 4
    data_storage_size_in_gb  = 20
    data_storage_size_in_tbs = 1
    db_workload              = "OLTP"
    is_auto_scaling_enabled  = false
    is_dev_tier              = true
  }
}

variable "autonomous_database_admin_password" {
  description = <<EOT
ADMIN password for Autonomous Database.
Must be 12 to 30 characters, include uppercase, lowercase and number.
It cannot contain double quotes, single quotes, or the word admin.
EOT

  type      = string
  sensitive = true

  validation {
    condition = (
      length(var.autonomous_database_admin_password) >= 12 &&
      length(var.autonomous_database_admin_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_admin_password)) &&
      can(regex("[a-z]", var.autonomous_database_admin_password)) &&
      can(regex("[0-9]", var.autonomous_database_admin_password)) &&
      !can(regex("\"", var.autonomous_database_admin_password)) &&
      !can(regex("'", var.autonomous_database_admin_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_admin_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_wallet_password" {
  description = <<EOT
Wallet password for Autonomous Database.
Must be 12 to 30 characters, include uppercase, lowercase and number.
It cannot contain double quotes, single quotes, or the word admin.
EOT

  type      = string
  sensitive = true

  validation {
    condition = (
      length(var.autonomous_database_wallet_password) >= 12 &&
      length(var.autonomous_database_wallet_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_wallet_password)) &&
      can(regex("[a-z]", var.autonomous_database_wallet_password)) &&
      can(regex("[0-9]", var.autonomous_database_wallet_password)) &&
      !can(regex("\"", var.autonomous_database_wallet_password)) &&
      !can(regex("'", var.autonomous_database_wallet_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_wallet_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_developer_password" {
  description = <<EOT
ORA26AI application user password.
Must be 12 to 30 characters, include uppercase, lowercase and number.
It cannot contain double quotes, single quotes, or the word admin.
EOT

  type      = string
  sensitive = true

  validation {
    condition = (
      length(var.autonomous_database_developer_password) >= 12 &&
      length(var.autonomous_database_developer_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_developer_password)) &&
      can(regex("[a-z]", var.autonomous_database_developer_password)) &&
      can(regex("[0-9]", var.autonomous_database_developer_password)) &&
      !can(regex("\"", var.autonomous_database_developer_password)) &&
      !can(regex("'", var.autonomous_database_developer_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_developer_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "application_username" {
  description = "Oracle AI Accelerator application login username."
  type        = string
  default     = "admin"

  validation {
    condition     = var.application_username == "admin"
    error_message = "Oracle AI Accelerator application username must be admin."
  }
}

############################################
# Virtual Cloud Network
############################################

variable "_oci_vcn" {
  description = "VCN defaults from upstream setup-tf."

  default = {
    display_name      = "vcn-oracle-ai"
    cidr_block        = "10.0.0.0/24"
    ingress_tcp_ports = [22, 80, 443, 8501]
  }
}

############################################
# Compute Instance
############################################

variable "_oci_instance" {
  description = "Compute instance defaults for the CloudTechNext test profile."

  default = {
    display_name = "oracle-linux-9-app"
    shape = {
      name          = "VM.Standard.E5.Flex"
      ocpus         = 2
      memory_in_gbs = 16
    }
  }
}
